# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTest1():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test1(self):
        self.driver.get("http://192.168.1.110:4200/login")
        self.driver.maximize_window()
        self.driver.find_element(By.NAME, "phone").send_keys("*****")
        self.driver.find_element(By.NAME, "pwd").send_keys("******")
        self.driver.find_element(By.CSS_SELECTOR, ".primaryBtnShadow").click()
        time.sleep(5)


if __name__ == '__main__':
    pytest.main(['-v', '-s', 'test_test1.py'])
