# Generated by Django 3.2.7 on 2022-01-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
